package com.yzc.entity;
// default package
// Generated 2019-9-27 10:33:55 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private int id;
	private String username;
	private String password;
	private Integer credit;
	private Set TOrders = new HashSet(0);

	public TUser() {
	}

	public TUser(int id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}

	public TUser(int id, String username, String password, Integer credit, Set TOrders) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.credit = credit;
		this.TOrders = TOrders;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getCredit() {
		return this.credit;
	}

	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	public Set getTOrders() {
		return this.TOrders;
	}

	public void setTOrders(Set TOrders) {
		this.TOrders = TOrders;
	}

}
