package com.yzc.pojo;
// default package
// Generated 2019-9-27 10:33:55 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class UserVO implements java.io.Serializable {

	private int id;
	private String username;
	private String password;
	private Integer credit;
	private String mobile;
	private String address;

	public UserVO() {
	}

	public UserVO(int id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}

	public UserVO(int id, String username, String password, Integer credit, String mobile,String address) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.credit = credit;
		this.mobile = mobile;
		this.address = address;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getCredit() {
		return this.credit;
	}

	public void setCredit(Integer credit) {
		this.credit = credit;
	}	
	
	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
